@startuml
group Get configuration to communicate with GEC
	FeeSrv -> AzureST ++ : GET https:////<storage account>//.blob.core.windows.net/acquirers///<acquirer id>//.json
		note left
			__header__
			x-ms-version: 2019-07-07
			Authorization: Bearer //<access token for storage account>//
		end note

	AzureST --> FeeSrv -- : HTTP 200 (ok)
		note right
			__body__
			{
				"pspConfigForVerifyAndActivate": {
					"psp": "//don't care//",
					"broker": "//don't care//",
					"channel": "//don't care//",
					"password": "//don't care//"
				},
				"pspConfigForGetFeeAndClosePayment" : {
					"psp": "//<psp id>//",
					"broker": "//<psp broker id>//",
					"channel": "//<channel id>//",
					"password": "//don't care//"
				}
			}
		end note

	note over FeeSrv #Orange
		On any other failure, return HTTP 500 (server error) with specific error body. 
	end note
end
@enduml