package it.pagopa.swclient.mil.feecalculator.util;

public enum ExceptionType {
	CLIENT_WEB_APPLICATION_EXCEPTION_400,
	CLIENT_WEB_APPLICATION_EXCEPTION_404,
	CLIENT_WEB_APPLICATION_EXCEPTION_500,
	TIMEOUT_EXCEPTION,
	UNPARSABLE_EXCEPTION,
}
